services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=teste
    #   - MONGO_INITDB_ROOT_PASSWORD=teste

volumes:
  mongodb_data: